# Collaborative Project

## Project Description

The following collaborative project focused on the digital humanity tool Palladio.  Palladio is able to take large amounts of information, such as a list of famous authors, as well as their dates and places of birth and death, and organize them, whether it is through a map, table, or timespan.  The tool is effective in visualizing data in a way that is easy to read, and the project can easily be accessed and saved onto any device.  However is limited in the ways if can be organized, as well as not being able to function on every browser.

## Collaboration Statement

Collaborative scholarship is a helpful learning method when tackling a large topic.  With the Palladio tool, which had a variety of features that needed to be explained and demonstrated, working as a team made it easy to split up the work into different sections.  Now, every member in the group knew how to generally use the tool, while each individual claimed the role of an expert in one specific area, whether it was how to create the project, what each visualization feature could present, or a different area.  Having a team to work on this project in a collaborative manner meant that the research of the tool was more in-depth, as group members would point out any new findings for other members that they may have missed upon first inspection.  Most importantly, collaborative scholarship is important because it teaches people how to work with one another.  As a group, we were able to allocate everyone to a part of the presentation where they felt strongest.  In addition, the group was in constant communication throughout the project, in order to make sure that the final presentation would be ready on time and that everything that needed to be included was presented.  Collaborative scholarship relieves some of the stress or anxiety that may arise when dealing with a large topic such as Palladio and gave each individual group member the confidence that they were giving a quality presentation and demonstration of the tool.
